### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by davidchaiken** [davidjbradshaw/eslint-formatter-summary-chart#6]
Thanks for this formatter! The functionality was helpful for me when introducing eslint into my project.

I think that there might be an error in the case when eslint finds no errors?
```
$ yarn run eslint --format summary-chart src scripts
yarn run v1.22.10
$ [...base_path...]/node_modules/.bin/eslint --format summary-chart src scripts
==== Files ====

Oops! Something went wrong! :(

ESLint: 7.31.0

RangeError: Invalid array length
    at [...base_path...]/node_modules/bar-horizontal/index.js:55:20
    at arrayMap ([...base_path...]/node_modules/lodash/lodash.js:653:23)
    at Function.map ([...base_path...]/node_modules/lodash/lodash.js:9622:14)
    at module.exports ([...base_path...]/node_modules/bar-horizontal/index.js:52:19)
    at module.exports ([...base_path...]/node_modules/eslint-formatter-summary-chart/lib/display.js:5:3)
    at module.exports ([...base_path...]/node_modules/eslint-formatter-summary-chart/lib/index.js:15:3)
    at Object.format ([...base_path...]/node_modules/eslint/lib/eslint/eslint.js:648:24)
    at printResults ([...base_path...]/node_modules/eslint/lib/cli.js:179:30)
    at async Object.execute ([...base_path...]/node_modules/eslint/lib/cli.js:314:13)
    at async main ([...base_path...]/node_modules/eslint/bin/eslint.js:132:24)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Let me know if you want me to try to find the bug and to submit a PR to fix it.

**Comment by davidjbradshaw** [comment]
Just seen this, PR would be great

**Comment by davidchaiken** [comment]
Oh, hey! It has been a while. :) I stopped using `--format` in my Makefile due to this issue. Now that you've expressed interested, I can dig in a bit and figure out if a PR is straightforward.

**Comment by davidjbradshaw** [comment]
Thanks for the fix, released as v0.3.0.

I also added aslant-config-auto and fixed the resulting errors.

**Comment by davidjbradshaw** [comment]
.

**Comment by davidchaiken** [comment]
Thanks!
